schema_version = "1.0.0"
id = "clothdrop_reborn"
version = "2.0.0"
name = "ClothDrop Reborn"
tagline = "Single-click cloth simulation tool"
maintainer = "Hartface <hartface@gmail.com>"
type = "add-on"

license = ["SPDX:GPL-3.0-or-later"]

tags = ["Physics"]

blender_version_min = "4.2.0"

#website = "https://github.com//clothdrop"

